language: R
sudo: required
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # install tmap dependencies
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libv8-3.14-dev
  # install tmap dependencies; for 16.04 libjq-dev this ppa is needed:
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libjq-dev
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - seb@poissonconsulting.ca
    on_success: change
    on_failure: always
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
