language: R
sudo: required
cache: packages

before_install:
  # units/udunits2 dependency:
  - sudo apt-get install --yes libudunits2-dev
  # sf dependencies:
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - seb@poissonconsulting.ca
    on_success: change
    on_failure: always
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always
