language: R
sudo: required
cache: packages

r_packages:
  - covr

before_install:
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    recipients:
      - seb@poissonconsulting.ca
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always

